[project]
name = "geospatial-wheels-index"
version = "0.1.0"
description = "Generate a pip simple index from cgohlke/geospatial-wheels"
requires-python = ">=3.11"
dependencies = [
    "pandas>=3.0.6",
    "pygithub>=2.10.0",
    "semver>=3.1.0",
]
optional-dependencies = {dev = ["myst-parser", "nbsphinx", "notebook", "pandas-stubs", "pydata-sphinx-theme", "pytest", "ruff", "sphinx", "sphinx-copybutton", "uv"]}
